//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::t_capital_rule::Entity as TCapitalRule;
pub use super::t_capital_rule_chain::Entity as TCapitalRuleChain;
pub use super::t_table_info::Entity as TTableInfo;
