//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_capital_rule_chain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub rule_id: String,
    pub chain_order: i32,
    pub start: i8,
    pub end: i8,
    pub table_info_id: i64,
    pub domain: String,
    pub sub_domain: String,
    pub table_info_name: String,
    pub table_fields: String,
    pub create_at: DateTimeUtc,
    pub update_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
