//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "t_table_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub domain: String,
    pub sub_domain: String,
    pub table_info_name: String,
    pub table_fields: String,
    pub create_at: DateTimeUtc,
    pub update_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
